<?php
namespace Semir\Laravel2impala\ThriftGenerated;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Semir\Laravel2impala\Thrift\Base\TBase;
use Semir\Laravel2impala\Thrift\Type\TType;
use Semir\Laravel2impala\Thrift\Type\TMessageType;
use Semir\Laravel2impala\Thrift\Exception\TException;
use Semir\Laravel2impala\Thrift\Exception\TProtocolException;
use Semir\Laravel2impala\Thrift\Protocol\TProtocol;
use Semir\Laravel2impala\Thrift\Protocol\TBinaryProtocolAccelerated;
use Semir\Laravel2impala\Thrift\Exception\TApplicationException;

class BeeswaxService_fetch_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'query_id',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\ThriftGenerated\QueryHandle',
        ),
        2 => array(
            'var' => 'start_over',
            'isRequired' => false,
            'type' => TType::BOOL,
        ),
        3 => array(
            'var' => 'fetch_size',
            'isRequired' => false,
            'type' => TType::I32,
        ),
    );

    /**
     * @var \ThriftGenerated\QueryHandle
     */
    public $query_id = null;
    /**
     * @var bool
     */
    public $start_over = null;
    /**
     * @var int
     */
    public $fetch_size = -1;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['query_id'])) {
                $this->query_id = $vals['query_id'];
            }
            if (isset($vals['start_over'])) {
                $this->start_over = $vals['start_over'];
            }
            if (isset($vals['fetch_size'])) {
                $this->fetch_size = $vals['fetch_size'];
            }
        }
    }

    public function getName()
    {
        return 'BeeswaxService_fetch_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->query_id = new \ThriftGenerated\QueryHandle();
                        $xfer += $this->query_id->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::BOOL) {
                        $xfer += $input->readBool($this->start_over);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->fetch_size);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('BeeswaxService_fetch_args');
        if ($this->query_id !== null) {
            if (!is_object($this->query_id)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('query_id', TType::STRUCT, 1);
            $xfer += $this->query_id->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->start_over !== null) {
            $xfer += $output->writeFieldBegin('start_over', TType::BOOL, 2);
            $xfer += $output->writeBool($this->start_over);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->fetch_size !== null) {
            $xfer += $output->writeFieldBegin('fetch_size', TType::I32, 3);
            $xfer += $output->writeI32($this->fetch_size);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
