<?php
namespace Semir\Laravel2impala\ThriftGenerated;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class BeeswaxService_executeAndWait_args
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'query',
            'isRequired' => false,
            'type' => TType::STRUCT,
            'class' => '\ThriftGenerated\Query',
        ),
        2 => array(
            'var' => 'clientCtx',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var \ThriftGenerated\Query
     */
    public $query = null;
    /**
     * @var string
     */
    public $clientCtx = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['query'])) {
                $this->query = $vals['query'];
            }
            if (isset($vals['clientCtx'])) {
                $this->clientCtx = $vals['clientCtx'];
            }
        }
    }

    public function getName()
    {
        return 'BeeswaxService_executeAndWait_args';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->query = new \ThriftGenerated\Query();
                        $xfer += $this->query->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->clientCtx);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('BeeswaxService_executeAndWait_args');
        if ($this->query !== null) {
            if (!is_object($this->query)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('query', TType::STRUCT, 1);
            $xfer += $this->query->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->clientCtx !== null) {
            $xfer += $output->writeFieldBegin('clientCtx', TType::STRING, 2);
            $xfer += $output->writeString($this->clientCtx);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
