<?php
namespace Semir\Laravel2impala\ThriftGenerated;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Semir\Laravel2impala\Thrift\Base\TBase;
use Semir\Laravel2impala\Thrift\Type\TType;
use Semir\Laravel2impala\Thrift\Type\TMessageType;
use Semir\Laravel2impala\Thrift\Exception\TException;
use Semir\Laravel2impala\Thrift\Exception\TProtocolException;
use Semir\Laravel2impala\Thrift\Protocol\TProtocol;
use Semir\Laravel2impala\Thrift\Protocol\TBinaryProtocolAccelerated;
use Semir\Laravel2impala\Thrift\Exception\TApplicationException;

interface ImpalaServiceIf extends BeeswaxServiceIf
{
    /**
     * @param Semir\Laravel2impala\ThriftGenerated\QueryHandle $query_id
     * @return Semir\Laravel2impala\ThriftGenerated\TStatus
     * @throws Semir\Laravel2impala\ThriftGenerated\BeeswaxException
     */
    public function Cancel(QueryHandle $query_id);
    /**
     * @return Semir\Laravel2impala\ThriftGenerated\TStatus
     */
    public function ResetCatalog();
    /**
     * @param Semir\Laravel2impala\ThriftGenerated\TResetTableReq $request
     * @return Semir\Laravel2impala\ThriftGenerated\TStatus
     */
    public function ResetTable(TResetTableReq $request);
    /**
     * @param Semir\Laravel2impala\ThriftGenerated\QueryHandle $query_id
     * @return string
     * @throws Semir\Laravel2impala\ThriftGenerated\BeeswaxException
     */
    public function GetRuntimeProfile(QueryHandle $query_id);
    /**
     * @param Semir\Laravel2impala\ThriftGenerated\QueryHandle $handle
     * @return Semir\Laravel2impala\ThriftGenerated\TInsertResult
     * @throws Semir\Laravel2impala\ThriftGenerated\QueryNotFoundException
     * @throws Semir\Laravel2impala\ThriftGenerated\BeeswaxException
     */
    public function CloseInsert(QueryHandle $handle);
    /**
     * @return Semir\Laravel2impala\ThriftGenerated\TPingImpalaServiceResp
     */
    public function PingImpalaService();
    /**
     * @param Semir\Laravel2impala\ThriftGenerated\QueryHandle $handle
     * @return Semir\Laravel2impala\ThriftGenerated\TExecSummary
     * @throws Semir\Laravel2impala\ThriftGenerated\QueryNotFoundException
     * @throws Semir\Laravel2impala\ThriftGenerated\BeeswaxException
     */
    public function GetExecSummary(QueryHandle $handle);
}
