<?php
namespace Semir\Laravel2impala\ThriftGenerated;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class QueryState
{
    const CREATED = 0;

    const INITIALIZED = 1;

    const COMPILED = 2;

    const RUNNING = 3;

    const FINISHED = 4;

    const EXCEPTION = 5;

    static public $__names = array(
        0 => 'CREATED',
        1 => 'INITIALIZED',
        2 => 'COMPILED',
        3 => 'RUNNING',
        4 => 'FINISHED',
        5 => 'EXCEPTION',
    );
}

