<?php
namespace Semir\Laravel2impala\ThriftGenerated;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface TCLIServiceIf
{
    /**
     * @param \ThriftGenerated\TOpenSessionReq $req
     * @return \ThriftGenerated\TOpenSessionResp
     */
    public function OpenSession(\ThriftGenerated\TOpenSessionReq $req);
    /**
     * @param \ThriftGenerated\TCloseSessionReq $req
     * @return \ThriftGenerated\TCloseSessionResp
     */
    public function CloseSession(\ThriftGenerated\TCloseSessionReq $req);
    /**
     * @param \ThriftGenerated\TGetInfoReq $req
     * @return \ThriftGenerated\TGetInfoResp
     */
    public function GetInfo(\ThriftGenerated\TGetInfoReq $req);
    /**
     * @param \ThriftGenerated\TExecuteStatementReq $req
     * @return \ThriftGenerated\TExecuteStatementResp
     */
    public function ExecuteStatement(\ThriftGenerated\TExecuteStatementReq $req);
    /**
     * @param \ThriftGenerated\TGetTypeInfoReq $req
     * @return \ThriftGenerated\TGetTypeInfoResp
     */
    public function GetTypeInfo(\ThriftGenerated\TGetTypeInfoReq $req);
    /**
     * @param \ThriftGenerated\TGetCatalogsReq $req
     * @return \ThriftGenerated\TGetCatalogsResp
     */
    public function GetCatalogs(\ThriftGenerated\TGetCatalogsReq $req);
    /**
     * @param \ThriftGenerated\TGetSchemasReq $req
     * @return \ThriftGenerated\TGetSchemasResp
     */
    public function GetSchemas(\ThriftGenerated\TGetSchemasReq $req);
    /**
     * @param \ThriftGenerated\TGetTablesReq $req
     * @return \ThriftGenerated\TGetTablesResp
     */
    public function GetTables(\ThriftGenerated\TGetTablesReq $req);
    /**
     * @param \ThriftGenerated\TGetTableTypesReq $req
     * @return \ThriftGenerated\TGetTableTypesResp
     */
    public function GetTableTypes(\ThriftGenerated\TGetTableTypesReq $req);
    /**
     * @param \ThriftGenerated\TGetColumnsReq $req
     * @return \ThriftGenerated\TGetColumnsResp
     */
    public function GetColumns(\ThriftGenerated\TGetColumnsReq $req);
    /**
     * @param \ThriftGenerated\TGetFunctionsReq $req
     * @return \ThriftGenerated\TGetFunctionsResp
     */
    public function GetFunctions(\ThriftGenerated\TGetFunctionsReq $req);
    /**
     * @param \ThriftGenerated\TGetOperationStatusReq $req
     * @return \ThriftGenerated\TGetOperationStatusResp
     */
    public function GetOperationStatus(\ThriftGenerated\TGetOperationStatusReq $req);
    /**
     * @param \ThriftGenerated\TCancelOperationReq $req
     * @return \ThriftGenerated\TCancelOperationResp
     */
    public function CancelOperation(\ThriftGenerated\TCancelOperationReq $req);
    /**
     * @param \ThriftGenerated\TCloseOperationReq $req
     * @return \ThriftGenerated\TCloseOperationResp
     */
    public function CloseOperation(\ThriftGenerated\TCloseOperationReq $req);
    /**
     * @param \ThriftGenerated\TGetResultSetMetadataReq $req
     * @return \ThriftGenerated\TGetResultSetMetadataResp
     */
    public function GetResultSetMetadata(\ThriftGenerated\TGetResultSetMetadataReq $req);
    /**
     * @param \ThriftGenerated\TFetchResultsReq $req
     * @return \ThriftGenerated\TFetchResultsResp
     */
    public function FetchResults(\ThriftGenerated\TFetchResultsReq $req);
    /**
     * @param \ThriftGenerated\TGetDelegationTokenReq $req
     * @return \ThriftGenerated\TGetDelegationTokenResp
     */
    public function GetDelegationToken(\ThriftGenerated\TGetDelegationTokenReq $req);
    /**
     * @param \ThriftGenerated\TCancelDelegationTokenReq $req
     * @return \ThriftGenerated\TCancelDelegationTokenResp
     */
    public function CancelDelegationToken(\ThriftGenerated\TCancelDelegationTokenReq $req);
    /**
     * @param \ThriftGenerated\TRenewDelegationTokenReq $req
     * @return \ThriftGenerated\TRenewDelegationTokenResp
     */
    public function RenewDelegationToken(\ThriftGenerated\TRenewDelegationTokenReq $req);
}
